Initial scores listing working state
tommybb/scores pull request #3
Opened 2017-08-14 14:26 UTC by tommybb

2017-08-16 03:39 UTC, cs3b requested changes
Elso have a look at ESLint errors - just by running tests

2017-08-16 03:39 UTC, cs3b commented on mirage/factories/pupil.js
> +  birthdate: new Date(),
it's usually better to have dynamic date

```` js
birthdate() {
  return new Date();
},
````

2017-08-16 03:41 UTC, cs3b commented on TIL.mb
> +- we need to define object in routes which in we return data found in store
it's good to go through [mirage documentation](http://www.ember-cli-mirage.com/docs/v0.3.x/)

2017-08-20 11:37 UTC, merged

2017-08-22 11:08 UTC, cs3b commented on app/components/table-score/row/template.hbs
> +{{yield}}
you don't need yield? could you explain why?

2017-08-22 11:08 UTC, cs3b commented on app/models/class-room.js
> +import DS from 'ember-data';
we need to setup eslint fully, and review the project config

2017-08-22 11:08 UTC, cs3b commented on mirage/factories/class-room.js
> +  name: '4B',
prefer random data - for faker or sequence

2017-08-22 11:08 UTC, cs3b commented on mirage/factories/score.js
> +  result: 1,
prefer dynamic generated data

2017-08-22 11:08 UTC, cs3b commented on mirage/factories/year.js
> +  name: '2016/2017'
similar here

2017-08-22 11:08 UTC, cs3b commented on package.json
>    "version": "0.0.0",
on every deploy to production it's good to bump version here

2017-08-22 11:08 UTC, cs3b commented on tests/integration/components/table-score/header/component-test.js
> +    // Set any properties with this.set('myProperty', 'value');
delete dead doce

2017-08-22 11:08 UTC, cs3b commented on tests/integration/components/table-score/header/component-test.js
> +    // Set any properties with this.set('myProperty', 'value');
would be good to spend one session on testing

2017-08-22 20:25 UTC, tommybb commented on app/components/table-score/row/template.hbs
> +{{yield}}
because I will not pass any block to my row??

2017-08-23 18:57 UTC, tommybb commented
@cs3b,  changes done in PR #4